### ISSUE TITLE
Negative values when analyzing time deltas between commits in a given project

### ISSUE THREAD

**Issue by iganchevup8** [MetricsGrimoire/CVSAnalY#101]
Hello,

not quite sure what causes this problem. I am analyzing a free software project and more specially time-deltas between commits. For an unknown reason I have negative values in some fields. When looking more carefully, there seems to be an issue with indexing system when inserting commits into the database. Here is an example:

6   475     2011-01-05 11:58:49     51 days 09:23:28
7   477     2011-01-07 16:28:31     2 days 04:29:42
8   478     2011-01-07 23:28:50     0 days 07:00:19
9   479     2011-01-10 21:38:55     2 days 22:10:05
10  480     2011-01-07 23:51:41     -3 days +02:12:46
11  481     2011-01-10 21:45:28     2 days 21:53:47
12  482     2011-01-10 21:57:03     0 days 00:11:35

The second column is the commit_id. The third column is the date of commit, the forth column is the time delta between commits. One can seen that commit 480 is indexed after commit 479, but in reality 480 occurs before 479. When reading the git log file everything seems to be in good order.

Do someone have an idea what causes this problem. Can provide more information if needed. Thanks.

Regards,
##

**Comment by jgbarah** [comment]
Are you having time zones into account? Remember that times in git are local to the repository where the commit happens, not UTC. Timezones are in the date_tz field.

If you're having tz into account, then we need to look for some other reason...

**Comment by iganchevup8** [comment]
Yes, both commits are from the same user, and thus, same time-zone. Here is an extract of the scmlog table:

```
        id      rev                               committer_id  author_id   date              date_tz   author_date     author_date_tz
474     475     80be042c240baab22bc51ed8d284abcd7c42350b    2   2   2011-01-05 11:58:49     -28800  2011-01-05 11:58:49     -28800
475     476     46305a05c5df422fabb754f83f826d858906b833    2   2   2011-01-05 12:12:43     -28800  2011-01-05 12:12:43     -28800
476     477     b88c1b5e3b731c0e1f6856bd63f81a9c32ba566e    2   2   2011-01-07 16:28:31     -28800  2011-01-07 16:28:31     -28800
477     478     4654755e7db570d7575b72b7656287b3f64a3da2    2   2   2011-01-07 23:28:50     -28800  2011-01-07 23:28:50     -28800
478     479     d9d78927d84fd68896abb62f79ebbed7c956500f    2   2   2011-01-10 21:38:55     -28800  2011-01-10 21:38:55     -28800
479     480     5885c7156ebf689c44d106062b030a27d26cdce7    2   2   2011-01-07 23:51:41     -28800  2011-01-07 23:51:41     -28800
480     481     6608e2a97e377d955c1d16d76db169f0b8d2d2e8    2   2   2011-01-10 21:45:28     -28800  2011-01-10 21:45:28     -28800
481     482     45d69beb2203ccc3a14766118c728883668ceba9    2   2   2011-01-10 21:57:03     -28800  2011-01-10 21:57:03     -28800
```

You can see that commit 480 occurred before commit 479, but was indexed as if it happened after it.

Here is a git log excerpt: http://pastebin.com/PcTT5RKP
Things seem OK.

Looking forward to provide more info if needed.

## 

**edit** Forgot to say that this is not the only negative value. There are many of them. On a file with 148 commits, there are 12 negative values. There are about 400 files, but didn't calculate for all of them, yet.

**Comment by jgbarah** [comment]
I see. Nothing related to TZ. Thanks for the clarification.

Re-reading your original comment, and this one, I'm not sure if I understand what you mean. It seems that you assume that the id field is a sequence number, or something? If this is the case, it is _not_. It is only a unique id for each commit, which is based on the order the git log is presented to the CVSAnalY parser. Since usually the git log is obtained for all the branches, specific commits could have weird orders. And in any case, no care is taken in obtaining a meaningful sequence. If you're interested in recovering the sequence of commits in some specific branch, you need to look at the commit_graph table, which holds child-parent relationships for commits. But I have to warn you that that table, although probably correct, has had very little testing, as far as I know.

If for some reason commit-time is enough for you, you only have to order commits according to that field before counting deltas (but I´m not sure if deltas between commits in potentially different branches may make sense).

But maybe I'm wrong again. So, if this is not the case, please specify what you would expect, and what you are finding weird...

**Comment by iganchevup8** [comment]
Hello Jesus,

> It seems that you assume that the id field is a sequence number, or something? If this is the case, it is not.

Yes, I was clearly assuming that the ID is a sequence number that represents the order of commits. Already analyzed couple of svn projects and IIRC this was the case. I might be wrong. Anyway your comment explains everything. I just need to re-index on date column. I downloaded only a particular branch and cvsanaly supposedly analyzed only this branch. There should be no commits from different branches in it.

Thank for you comment. The ticket could be closed I think.

**Comment by jgbarah** [comment]
Please, have in mind that usually you're not "downloading only a particular branch". Usually, you clone the whole git repo, and then checkout some specific branch (even if you do that with only one operation). In this respect, git works differently from svn. In fact, for svn, it is likely that the order in CVSAnalY database reflects the sequence order, because of the way svn log parsing works in CVSAnalY (but I shouldn't rely on that either).

In any case, thanks a lot for your comments.
