### ISSUE TITLE
Changed code metric

### ISSUE THREAD

**Issue by rodrigokuroda** [MetricsGrimoire/CVSAnalY#93]
Hi,
Is there an extension or a complementary tool for CVSAnalY to calculate the changed code metric (a.k.a. code churn - added, removed, and changed lines) for each file revision?

**Comment by jgbarah** [comment]
Hi, Rodrigo. You better make this kind of questions in the mailing list: https://lists.libresoft.es/listinfo/metrics-grimoire

In any case, probably you are looking after the CommitsLOC extension, have a look in the extensions directory. It provides you with lines added / removed per file per commit, according to what you can measure from the commit patch (that is, they are wc lines). Have into account that you cannot really know about "changed lines" without further treatment (and a lot of guesses), because in the patch you only see lines added / lines removed.

I'm closing this ticket, and I suggest to follow on in the mailing list, but feel free to reopen if you need clarification.
